name: '🧑‍🏭'
on: [ push ]
jobs:
  ci:
    permissions:
      id-token: write
      deployments: write
    runs-on: ubuntu-latest
    steps:

      - name: 'Fetch latest'
        uses: actions/checkout@v6

      - name: 'Setup Go'
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: 'Run tests'
        run: ./scripts/test.sh

      - name: 'Build website'
        if: github.ref == 'refs/heads/trunk'
        run: ./scripts/build.sh

      - name: 'Publish image'
        if: github.ref == 'refs/heads/trunk'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: >
          skopeo copy
          --dest-creds "$DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN"
          oci-archive:image.tar.gz
          docker://docker.io/$DOCKERHUB_USERNAME/website:latest

#      - name: 'Trigger deployment'
#        if: github.ref == 'refs/heads/trunk'
#        run: >
#          curl
#          --fail
#          --head
#          --no-progress-meter
#          --header "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}"
#          "${{ secrets.WATCHTOWER_URL }}"
